### ISSUE TITLE
Update nix-on-droid's termux version

### ISSUE THREAD

**Issue by c4dr01d** [t184256/nix-on-droid#103]
I see the nix-on-droid depend the very old termux version, when I want input some CJK characters in nix-on-droid, I must input in another app and cut to nix-on-droid, because app use rom builtin security keyboard, The newest version of termux allow user can use daily keyboard like rime (for my situation). So have plan to upgrade the base termux version?

**Comment by ShamrockLee** [comment]
> I see the nix-on-droid depend the very old termux version, when I want input some CJK characters in nix-on-droid, I must input in another app and cut to nix-on-droid, because app use rom builtin security keyboard, The newest version of termux allow user can use daily keyboard like rime (for my situation). So have plan to upgrade the base termux version?

I'm able to use software keyboards including Hacker's Keyboard and Trime inside the NixOnDroid on my phone.

**Comment by c4dr01d** [comment]
@ShamrockLee I just using trime for my main keyboard, I don't know how to change the default keyboard to trime(So I doubt the termux version is lower....

**Comment by ShamrockLee** [comment]
@c4dr01d Would it work by (temporarity) disabling the serure keyboard?

**Comment by c4dr01d** [comment]
@ShamrockLee Cannot, when I disabled, the system tell me have security risk
