### ISSUE TITLE
Flake configuration activation error

### ISSUE THREAD

**Issue by c4dr01d** [t184256/nix-on-droid#108]
I changed my nix-on-droid configuration to flake, after build at activate it, I got the error, detail:
```
error: getting status of '/data/data/com.termux.nix/files/home/result': No such file or directory
```

**Comment by Bobbbay** [comment]
Can you try `ls result`?

**Comment by c4dr01d** [comment]
@Bobbbay Sorry for waiting a long time, here is the `ls result` result:
![Screenshot_20210606_104025_com termux nix](https://user-images.githubusercontent.com/50952350/120910722-c581dd00-c6b3-11eb-9f3c-381371a979b2.jpg)

**Comment by c4dr01d** [comment]
Maybe activate script was hard coded the path?
