### ISSUE TITLE
Nix database directory '/nix/var/nix/db' is not writable: No such file or directory

### ISSUE THREAD

**Issue by pjones** [t184256/nix-on-droid#109]
I'm trying to get a local build working so I can contribute to the project.  When I use the `build.sh` script I get this error:

```
$ ./build.sh                                                             
aarch64: building proot...        
aarch64: patching proot path in modules/environment/login/default.nix...
           aarch64 = "/nix/store/kvpss7dny298p9gwg1hd2x54pvlw5q4g-proot-termux-unstable-2020-
10-25-aarch64-unknown-linux-android";
           aarch64 = "/nix/store/kvpss7dny298p9gwg1hd2x54pvlw5q4g-proot-termux-unstable-2020-
10-25-aarch64-unknown-linux-android";
aarch64: autodetected repository: pjones/nix-on-droid.git
aarch64: autodetected channel URL: https://github.com/pjones/nix-on-droid.git/archive/master.
tar.gz
aarch64: building nix-on-droid...
builder for '/nix/store/c9q55nbqdbzh47i0qfyjynswwcpi2vh9-nix-directory.drv' failed with exit 
code 1; last 10 log lines:
  unpacking source archive /nix/store/d4jljrixqld1ak15hx4ha3dl9sp4ccil-nix-2.3.6-aarch64-linu
x.tar.xz
  source root is nix-2.3.6-aarch64-linux
  setting SOURCE_DATE_EPOCH to timestamp 1591134336 of file nix-2.3.6-aarch64-linux/install-s
ystemd-multi-user.sh
  patching sources
  configuring
  no configure script, doing nothing
  building
  GC Warning: pthread_getattr_np or pthread_attr_getstack failed for main thread
  GC Warning: Couldn't read /proc/stat
  error: Nix database directory '/nix/var/nix/db' is not writable: No such file or directory
[0 built (1 failed), 0.0 MiB DL]
error: while evaluating the attribute 'buildCommand' of the derivation 'bootstrap-zip' at /ni
x/store/xgkwj8zns3mv8ilg086rgxf15d3sqbg7-source/pkgs/build-support/trivial-builders.nix:7:7:
while evaluating the attribute 'buildCommand' of the derivation 'bootstrap' at /nix/store/xgk
wj8zns3mv8ilg086rgxf15d3sqbg7-source/pkgs/build-support/trivial-builders.nix:7:7:
build of '/nix/store/c9q55nbqdbzh47i0qfyjynswwcpi2vh9-nix-directory.drv' failed
```

I'm running the script on a NixOS x86_64 machine.

(NOTE: I did have to update the pinned nixpkgs version due to [this bug](https://github.com/NixOS/nixpkgs/issues/92458).  I'm not sure if that may be contributing to the issue.  However, with an updated nixpkgs I get past the Python core dump and get to the failure in `nix-directory`.)

Thanks for this wonderful project!

**Comment by Gerschtli** [comment]
As a quick fix you could just add `https://nix-on-droid.cachix.org` with `nix-on-droid.cachix.org-1:56snoMJTXmDRC1Ei24CmKoUqvHJ9XCp+nidK7qkMQrU=` as key to your substituters. With this you get a working version.

Updating the pinned nixpkgs and all the other packages like nix, qemu, termux etc. should be done but takes a bit more time. I tried it in october last year but wasn't successful. Can't remember what it was, but if you want to give it a try, feel free :)

**Comment by Gerschtli** [comment]
@pjones Is this still an issue? We updated nixpkgs a few days ago.

**Comment by pjones** [comment]
As soon as I get a chance I'll update to the latest commit and give it a try.  Thank you!

**Comment by pjones** [comment]
Everything builds successfully now.  Thank you so much!
