### ISSUE TITLE
basic tools missing

### ISSUE THREAD

**Issue by ShalokShalom** [t184256/nix-on-droid#110]
Chsh, which and similar tools are not available by default.

After looking in a couple of other issues, I figured out there is this package called unixtools, a meta package that is supposed to provide those tools cross platform.

Upon installing, it didnt work.
Still no chsh and which.

Other apps work.
I suggest to preinstall tools like this.

**Comment by t184256** [comment]
-1 from me, it's a slippery slope towards preinstalling all kinds of opinionated tools. I think so far we've stuck to the bare minimum Nix needs + vi. We don't even have grep & find.

But if you are missing these tools specifically, and they're hard to discover, consider adding them commented out to the default config template, with a comment detailing what they provide. That's also a slippery slope, but at least one that doesn't impact bootstrapping.

**Comment by ShalokShalom** [comment]
You missed all but the first and the last sentence.

I actually installed them, and they are still not available

```
After looking in a couple of other issues, I figured out there is this package called unixtools, a meta package that is supposed to provide those tools cross platform.

Upon installing, it didnt work.
Still no chsh and which.

Other apps work.
```

**Comment by Gerschtli** [comment]
chsh will not work, you should use the `user.shell` option.

I don't know unixtools or what package you want to use but keep in mind, not every package will (out-of-the-box) work on an android device within a proot environment without a real user management (and root access).

**Comment by t184256** [comment]
I'm afraid there's no metapackage called `unixtools` and one cannot install it. There are [several packages grouped under `unixtools`](https://search.nixos.org/packages?channel=20.09&query=unixtools), and which is not among them.

We need more info on what you're trying to achieve, what are you doing, what are you expecting and what are you suggesting.

**Comment by ShalokShalom** [comment]
You can install unixtools as a meta, just try it.
And I mean utillinux, as said.

**Comment by Gerschtli** [comment]
Installing utillinux works perfectly, which is not part of this package.

Could you elaborate what the problem is exactly? If you need which, just install the package `which`.

**Comment by ShalokShalom** [comment]
No, I was speaking about chsh. 
It seems the issue is already resolved  by your college. 

I still recommend preinstalling the absolute basics.

This is about standards.
