### ISSUE TITLE
Build and Switch failed: Function not implemented

### ISSUE THREAD

**Issue by 18fadly-anthony** [t184256/nix-on-droid#112]
# Here are screenshots of the error and of the config file.
![Screenshot-2021-05-13-16-56-40](https://user-images.githubusercontent.com/31709415/118201982-5ca69c80-b448-11eb-8efd-ec342c5c46eb.jpeg)
![Screenshot-2021-05-13-16-57-53](https://user-images.githubusercontent.com/31709415/118202006-67613180-b448-11eb-8179-f91ada55e4c3.jpeg)

**Comment by t184256** [comment]
Sounds like #91.

**Comment by Gerschtli** [comment]
Solved via #91, please reopen if still a problem
