### ISSUE TITLE
Shmem feature-request

### ISSUE THREAD

**Issue by ahdyt** [t184256/nix-on-droid#114]
Any occasion on enabling shmem again? as current shmem known as "Function Not Implemented".

What is this use for? something like postgresql. // initdb with postgresql inside nix-shell will shows you error about shmem.

refs: https://github.com/termux/libandroid-shmem/issues/11

**Comment by t184256** [comment]
Not an expert as well, but that lib could be some bionic ease-of-porting lib, so I'd like to first kindly ask the reporter to reproduce with the current master so that https://github.com/t184256/nix-on-droid/pull/138 is included and provide more context if it's still a problem.

**Comment by t184256** [comment]
Bad news are, I can reproduce the bug, it's not fixed. Guess we need that `--sysvipc` after all.

Good news are, `build.extraProotOptions = [ "--sysvipc" ];`, `nix-on-droid switch` and restarting the app is enough to fix it.

**Comment by Gerschtli** [comment]
Does it any harm if we enable it by default? And what does this flag in the first place?

**Comment by t184256** [comment]
Enables a proot extension specific for proot-termux intercepting and doing something to interprocess communication-related functions. These aren't widely used and this is the kind of stuff I'd blindly enable in master post-release and wait for bugreports.
