### ISSUE TITLE
htop: 6147 illegal hardware instruction  htop

### ISSUE THREAD

**Issue by bbigras** [t184256/nix-on-droid#123]
![Screenshot_20210626-164713.png](https://user-images.githubusercontent.com/24027/123525374-b3e29280-d6bf-11eb-8330-3c49acc99b37.png)

**Comment by t184256** [comment]
`file $(realpath htop)`, please.

What's your architecture?

**Comment by t184256** [comment]
Sorry, `file $(realpath $(command -v htop))`.

**Comment by bbigras** [comment]
```
❯ file $(realpath $(command -v htop))
/nix/store/ngkjdhwxdwm39iqm6p4cw0ax5isz23i2-htop-2.2.0/bin/htop: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /nix/store/ikl21vjfq900ccbqg1xasp83kadw6q8y-glibc-2.32-46/lib/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, not stripped

❯ uname -a
Linux localhost 4.4.223-g52750b8f2138-ab6846512 #1 SMP PREEMPT Fri Sep 18 09:49:34 UTC 2020 aarch64 GNU/Linux
```

Pixel 2, android 11

**Comment by Gerschtli** [comment]
Which versions of nix-channels/flakes you are using? Does it work with the latest 21.05 release of nix-on-droid?

**Comment by t184256** [comment]
Tried on a clean install of 21.05, couldn't reproduce (/nix/store/5m59dfvmnnk9mrrzpd2ak98v9za4s11y-htop-2.2.0/bin/htop).

Interestingly, it seemed to build it, even though it seems to be in cachix.

**Comment by bbigras** [comment]
I'm following nixos-unstable with flakes. at 1905f5f2e55e0db0bb6244cfe62cb6c0dbda391d.

My config is at https://github.com/bbigras/nix-config . Since today, the github actions are building my nix-on-droid config too (since I saw that this repo does it too).

I'll try to find the time to test with 21.05 soon.

**Comment by t184256** [comment]
> Since today, the github actions are building my nix-on-droid config too

Wait, so that's where this x86 htop comes from?

> since I saw that this repo does it too

This one compiles the part that's cross-compiled.

**Comment by bbigras** [comment]
I had the problem with htop before today. I didn't realise it was x86. Maybe the problem is only with the overlays since I have been building and pushing from my computer to my phone for a while now.
