### ISSUE TITLE
fish-3.3.1 shell is not building successfully (failing low-level tests)

### ISSUE THREAD

**Issue by duckpuppy** [t184256/nix-on-droid#126]
I don't actually use the fish shell, but I do use direnv and the direnv derivation in nixpkgs tests against fish. I recently updated my channels and tried a rebuild, and get the following error now:

![Screenshot_20210714-101702_Nix](https://user-images.githubusercontent.com/19253/125638228-75854b3a-3a2a-43c2-94cd-9838a419a029.jpeg)

I know there are fish users here, but I'm having trouble getting past this issue. I think the problem here is a test that's testing a low-level feature that the NOD console isn't providing.

**Comment by duckpuppy** [comment]
I got past the error with the following snippet in my `nix-on-droid.nix` file.

```
  nixpkgs.overlays = [
    ( self: super: {
      direnv = super.direnv.overrideAttrs (oldAttrs: {
        checkInputs = [self.zsh];
        checkPhase = ''
          export HOME=$(mktemp -d)
          make test-go test-bash test-zsh
        '';
      });
    })
  ];

```

This removes the steps that test against fish, so it doesn't actually fix the fish build issue, just bypasses it in my case.

**Comment by Gerschtli** [comment]
Is this still a problem and could you give as a minimal config to reproduce that issue?

**Comment by Gerschtli** [comment]
Feel free to reopen if this is still an issue :)
