### ISSUE TITLE
Provide something like nixos `nix.package` option

### ISSUE THREAD

**Issue by NobbZ** [t184256/nix-on-droid#128]
Currently if one wants to use an unstable version of nix they have to manually `nix-shell` into it after each start. Just adding it to `environment.packages` doesn't seem to properly persist.

With `environment.packages = [ pkgs.nixUnstable ]` `nix --version` still reports 2.3.x. even after restarting the terminal.

I have to explicitly do `nix-shell -p nixUnstable` first.

nixOS Module system has [`nix.package`](https://search.nixos.org/options?channel=21.05&show=nix.package&from=0&size=50&sort=relevance&query=nix.package) for this.

**Comment by Gerschtli** [comment]
Please have a look at https://github.com/t184256/nix-on-droid/pull/129 :)
