### ISSUE TITLE
TODO: Build statically-linked qemu with Nix

### ISSUE THREAD

**Issue by t184256** [t184256/nix-on-droid#14]
$subj

**Comment by Gerschtli** [comment]
To be more precise for possible contributors: The qemu-aarch64-static binary is currently only downloaded in a compiled version, see https://github.com/t184256/nix-on-droid-bootstrap/blob/master/pkgs/qemu-aarch64-static.nix. We should aim for building everything with nix and should not use external built binaries.

**Comment by Gerschtli** [comment]
We are not using qemu for building the bootstrap zip anymore.
