### ISSUE TITLE
Flake setup for bootstrap build

### ISSUE THREAD

**Issue by Gerschtli** [t184256/nix-on-droid#148]
I figured it would be pretty cool, to set up the bootstrap build as flake outputs. Do you have any objections on that? Would you still want to be able to do it the old way or should we go flake-only (for the bootstrap build part).

**Comment by t184256** [comment]
No objections whatsoever.

**Comment by t184256** [comment]
Flake-only is fine.

**Comment by Gerschtli** [comment]
Implemented with #204
