### ISSUE TITLE
Getting conflicting packages

### ISSUE THREAD

**Issue by 573** [t184256/nix-on-droid#175]
6Getting this when `home-manager switch`:

>error: packages '/nix/store/nzk4sn9wjyvydrfyb2vgxnang18qask4-nix-on-droid-path/include/node/cppgc/common.h' and '/nix/store/74h0mdrdlnfdyxm3n1g7aynzlrf7sp8w-nodejs-16.13.2/include/node/cppgc/common.h' have the same priority 5; use 'nix-env --set-flag priority NUMBER INSTALLED_PKGNAME' to change the priority of one of the conflicting packages (0 being the highest priority)
builder for '/nix/store/rzxfigbzix2vk3mp867kmrmcbxyp57y3-user-environment.drv' failed with exit code 1
error: build of '/nix/store/rzxfigbzix2vk3mp867kmrmcbxyp57y3-user-environment.drv' failed

- system: `"aarch64-linux"`                                                - host os: `Linux 4.4.111-21427293`                                        - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`                                          - channels(nix-on-droid): `"nix-on-droid-21.11, nixpkgs-21.11.336020.2128d0aa28e"`
 - nixpkgs: `/nix/store/zjl9p0crqhw3q6acacjd25ppfz28rjf2-nixpkgs-src`

Additional context:  

I get lots of similar errors since I switched from `nix-on-droid switch` to `hm`

**Comment by Gerschtli** [comment]
Can you post your nix-on-droid.nix and the output of `nix-env -q`. It seems you are installing a package with nix-on-droid and nix-env both containing `/include/node/cppgc/common.h`.

**Comment by 573** [comment]
Thx for reaching out @Gerschtli 

I have nodejs-latest in my `home.packages` and the standard nix-on-droid.nix though including home.nix there.

Indeed the error occurs only with home-manager switch not with n-o-d switch.

**Comment by Gerschtli** [comment]
So you are using nix-on-droid without its home-manager module but with a separate home.nix? Either way, to help you debug, I would need your whole configuration.. It seems you are having some duplicate packages in nix-on-droid, home-manager and/or nix-env itself.

**Comment by 573** [comment]
@Gerschtli nevermind, if I get it correctly I would have to `nix-channel --add https://github.com/rycee/home-manager/archive/release-21.11.tar.gz home-manager` and then `--update` to have the module working (line in my config reads `home-manager.config = import ./home.nix;`) as intended ?

Also I have `nix.package = pkgs.nix_2_3;` so the command to use would be `nix-on-droid switch` anyway as `home-manager switch` could not pick that config up, is that so ?
