### ISSUE TITLE
Using Newer Nix Versions for Flake Evaluation

### ISSUE THREAD

**Issue by mtoohey31** [t184256/nix-on-droid#183]
Hello! I've been working on setting up a nix-on-droid configuration using flakes, and I ran into issues with evaluating flakes that use newer nix builtins. I'm currently using [this branch](https://github.com/mtoohey31/nix-on-droid/tree/remove-nix_2_4) for my own configuration, but that's not a solution for everyone, as merging that would break things for anyone using a version of nixpkgs whose current nix package doesn't support flakes.

I'm not sure what the best solution is, because we do need to force `nix_2_4` or higher for people on older nixpkgs versions, but we shouldn't force people who want to use newer versions into using `nix_2_4`. Maybe we could add a check in `nix-on-droid/default.nix` to check whether the version of `nix` provded in the `nix` input is 2.4 or later, then just don't use the `nix_2_4` input when it is? Just an idea, there might be a more elegant way to do it though.

**Comment by Gerschtli** [comment]
Do you know why we need >= 2.4? I can't recall what was the reason TBH :D

But your solution sounds about right then: Use default nix if >=2.4, elso use nix_2_4. Feel free to create a PR for that, would be worth adding that to the 22.05 release I think (@t184256).

**Comment by mtoohey31** [comment]
> Do you know why we need >= 2.4? I can't recall what was the reason TBH :D

I don't think nix <= 2.3 supports flakes, when I run `nix build .#` with nix 2.3.16, it errors out with: `don't know what to do with argument '.#'`.

> But your solution sounds about right then: Use default nix if >=2.4, elso use nix_2_4. Feel free to create a PR for that, would be worth adding that to the 22.05 release I think (@t184256).

Will do!

**Comment by t184256** [comment]
> would be worth adding that to the 22.05 release I think (@t184256).

Maybe even to this release; will have a deeper look at it sometime this week.
