### ISSUE TITLE
nix.nixPath does not set NIX_PATH correctly

### ISSUE THREAD

**Issue by strout** [t184256/nix-on-droid#190]
I'm using the config option `nix.nixPath` to set $NIX_PATH. It's supposed to be colon-separated if there are multiple entries in the list, but instead it's space separated. For example:

`nix.nixPath = ["nixpkgs=/foo" "home-manager=/bar"];`

should result in

`NIX_PATH="nixpkgs=/foo:home-manager=/bar"`

but it's currently

`NIX_PATH="nixpkgs=/foo home-manager=/bar"`

and the various nix-* tools can't understand it.

**Comment by Gerschtli** [comment]
I went for the Option 2, created a PR.
