### ISSUE TITLE
zsoelim collision detected

### ISSUE THREAD

**Issue by 573** [t184256/nix-on-droid#193]
>builder for '/nix/store/mmlqkzz0aavapzpm0vvnsp8853ibwc3y-nix-on-droid-path.drv' failed with exit code 25; last 1 log lines:
  error: collision between `/nix/store/v204gz3847njc734kzjl99bxglbv109g-man-db-2.9.4/libexec/man-db/zsoelim' and `/nix/store/zlmqhq9w1dgxcjgfgsn3mn8ckzws308i-man-db-2.10.2/libexec/man-db/zsoelim'
cannot build derivation '/nix/store/q4mwyld1hn8jnygvznq7nad2xgb1zxn3-nix-on-droid-generation.drv': 1 dependencies couldn't be built
[0 built (1 failed)]
error: build of '/nix/store/q4mwyld1hn8jnygvznq7nad2xgb1zxn3-nix-on-droid-generation.drv' failed

**Comment by t184256** [comment]
How are you pulling it in? Looks like you try to "coinstall" two into one profile.

**Comment by Gerschtli** [comment]
Maybe it is about time for an issue template so that there will not be anymore issues without a reproducible example or any context :)

**Comment by 573** [comment]
Sorry my miss, I had [this nix-on-droid.nix](https://gist.github.com/573/d89b70d5734eb67228bad58c4fdb6f98) and [this home.nix](https://gist.github.com/573/36e061401ab5c2192396dc796d466673) as well as this [default.nix for nvim](https://gist.github.com/573/f3fc92f93433a29f5ec6bafbf3fe29c4)

Also did an update back then (`nix-channel --list`):
```console
home-manager https://github.com/nix-community/home-manager/archive/release-22.05.tar.gz
home-manager-master https://github.com/nix-community/home-manager/archive/master.tar.gz
nix-on-droid https://github.com/t184256/nix-on-droid/archive/release-22.05.tar.gz
nixos-unstable https://nixos.org/channels/nixos-unstable
nixpkgs https://nixos.org/channels/nixos-22.05-aarch64
```

The collision was bypassed when I disabled `man` from the `environment.packages` in nix-on-droid.nix as well as the `systemd.user.services` entry in home.nix.

Other than that nix-on-droid is awesome !

**Comment by Gerschtli** [comment]
Could you post the output of `nix-env -q`? Other than that, I don't know where the other version of man-db comes from. The `systemd` should not be involved in fixing your issue, I think.

**Comment by 573** [comment]
`nix-on-droid-path` is all, is it bc I manage via home.nix ?

**Comment by Gerschtli** [comment]
To reduce potential problems like this, I recommend setting these values

```nix
{
  home-manager.useGlobalPkgs = true;
  home-manager.useUserPackages = true;
}
```

And use `<nixpkgs>` instead your custom instance of nixpkgs, to ensure that nix-on-droid uses the same instance everywhere (you can set `nixpkgs.config` and `nixpkgs.overlays` to modify the instance).

You could also run `which man` to see, where the man binary comes from.

**Comment by 573** [comment]
@Gerschtli I'm struggling to apply `nixpkgs.config` to `nixpkgs` itself, i. e. 
```nix
{
nixpks.config.packageOverrides = pkgs: {
   unstable = import sources."nixos-unstable" { config = config.nixpkgs.config; };
      nixpkgs = import sources.nixpkgs { config = config.nixpkgs.config; };
};
}
```
`home.packages = with pkgs; [unstable.someAttr];` seems to work as with `home.packages = with pkgs; [anotherAttr];` (just from pinned `pkgs` / `nixpkgs` here) I'm not sure about.

**Comment by 573** [comment]
Should probably convert this to a discussion (Q&A).

**Comment by Gerschtli** [comment]
1. You have a typo in `nixpks.config.packageOverrides`, should be `nixpkgs.config.packageOverrides`
2. I would recommend overlays instead of packageOverrides as they are more flexible and are composable (packageOverrides is deprecated AFAIK)
3. To understand why you are not just using NIX_PATH but `~/.config/nixpkgs/nix/sources.nix` it would be helpful, if you could paste the content of the file and/or describe the intention.

**Comment by 573** [comment]
I manage the pinned version of nixpkgs via [`niv`](../../../nmattia/niv) (uses sources.nix/sources.json as database)
```console
$ niv show nixpkgs
nixpkgs
  homepage: https://search.nixos.org/packages
  url: https://github.com/NixOS/nixpkgs/archive/fa15ff601e3.tar.gz
  owner: NixOS
  branch: nixpkgs-unstable
  url_template: https://github.com/<owner>/<repo>/archive/<rev>.tar.gz
  repo: nixpkgs
  type: tarball
  sha256: 0664axw7g9rvv0v646cbfghb8x6cdbmw1g78qspsbbk7fdkilj0k
  description: Nix Packages collection
  rev: fa15ff601e3
```

**Comment by 573** [comment]
Acc to https://nix-community.github.io/home-manager/nixos-options.html#nixos-opt-home-manager.useGlobalPkgs `nixpkgs.*` is disabled when `useGlobalPkgs = true`.

Would `nixpkgs.overlays = overlays; nixpkgs.config = pkgsConfig;` as in [this so answer](https://stackoverflow.com/a/48736203/3320256) still work ?

**Comment by Gerschtli** [comment]
Ah okay, so you are not using your channels from `.nix-channels` in your config but still for running nix-on-droid. (flakes would make this setup less confusing BTW :) ).

The `nixpkgs.*` options in home-manager will not be read, but the `nixpkgs.*` options in nix-on-droid will be. I am not reading this really long answer on SO, but setting these options in nix-on-droid config (not home-manager) should work.

**Comment by 573** [comment]
I'll have to approach flakes for my config I guess.
On question remains, I'm setting that up to test right now, will `nixpkgs.pkgs = import sources.nixpkgs { inherit (config.nixpkgs) config; };` work as well in nix-on-droid.nix

**Comment by Gerschtli** [comment]
There is currently no option called `nixpkgs.pkgs`.. Changing the nixpkgs version in the middle of evaluation does not work that easily I suppose.
