### ISSUE TITLE
Failed to switch to a local flake repo on a new installation (git not found)

### ISSUE THREAD

**Issue by contrun** [t184256/nix-on-droid#198]
I failed to switch to a local flake repo configuration. The reason seems to be nix-on-droid (or nix) depends git.

```
nix-on-droid switch --flake ./infra#nod
Building activation package...
error: getting the HEAD of the Git tree '/data/data/com.termux.nix/files/home/infra' failed with exit code 1:
       error: executing 'git': No such file or directory
```

Manually install git with `nix-env -iA nixpkgs.git` fixes this problem.

## How to reproduce
```
git clone https://github.com/contrun/infra
cd infra
git checkout a319ca6885afe3c15449f324e5b1dc9008a13290
nix-on-droid switch --flake .#nod
```

**Comment by Gerschtli** [comment]
What would you expect that should be done in nix-on-droid? There is only a need for git when you use a flake that is locally available as git project but to clone a git repo you need git.. So your steps to reproduce require git to run git clone. Maybe I am missing the point but this is only an issue if you uninstall git after git clone..

**Comment by contrun** [comment]
I expect nix-on-droid to be wrapped with git Is it too much for nix-on-droid?

Good point on the git clone process. I actually cloned my repo with `nix --extra-experimental-features nix-command --extra-experimental-features flakes run nixpkgs#git clone`. The reason I don't run `nix-env -iA nixkgs.git` is that this would cause a conflict as I want to install git with `nix-on-droid switch --flake ./infra#nod`. Otherwise, I may see error message like

```
error: packages '/nix/store/d0wb2gam2pyksz2dsjx6sa83761jrrgi-hello-2.12/bin/hello' and '/nix/store/61n15131n3b9mn7ajvddbyfnv2b3pgjd-hello-2.12/bin/hello' have the same priority 5
; use 'nix-env --set-flag priority NUMBER INSTALLED_PKGNAME' to change the priority of one of the conflicting packages (0 being the highest priority)
```

**Comment by Gerschtli** [comment]
I don't think it is reasonable to wrap nix-on-droid with git because it is only needed for flakes and I would assume that everyone using a local git repo for its flake has git available. Nonetheless I understand your bootstrap issue but why not use a nix shell, that way you don't need to install git manually globally on your device.

```sh
nix --extra-experimental-features nix-command --extra-experimental-features flakes run nixpkgs#git --command nix-on-droid switch --flake .#nod
```

**Comment by t184256** [comment]
So, will the proposal lead to the increase of the closure size or won't it?

**Comment by Gerschtli** [comment]
It would increase the closure size by the size of git closure.

**Comment by t184256** [comment]
Then I'm against; taht way we'd be taking flexibility away from the users and forcing a heavier bootstrap upon them.

If you find it logical for nix to always have git in the closure... I do admit there's logic in that, but then, please, push for that change in nixpkgs.
