### ISSUE TITLE
Failed to turn on BTI protection

### ISSUE THREAD

**Issue by dlip** [t184256/nix-on-droid#199]
I'm unable to get a shell on Samsung galaxy z flip 4

```
/data/data/com.termux.nix/files/usr/bin/sh: /nix/store/9b6mgv7wzg964rf292s9x49n5g8yfgkp-glibc-2.32-54/lib/ld-linux-aarch64.so.1: failed to turn on BTI protection

[Process completed (code 127) - press Enter]
```

**Comment by zhaofengli** [comment]
I encountered this problem as well on my Galaxy S22. The reason is that glibc 2.32 bundled in the Nix bootstrap tarball lacks a [recent fix](https://github.com/bminor/glibc/commit/cd543b5eb36). I'm working on a fix (bump to Nix 2.11.0) and will send a PR soon.

**Comment by zhaofengli** [comment]
I opened #200 to fix this.

**Comment by t184256** [comment]
Should be resolved, please clear the app data or reinstall, then bootstrap from `https://nix-on-droid.unboiled.info/bootstrap` or `https://nix-on-droid.unboiled.info/bootstrap-testing`.
