### ISSUE TITLE
docs: terminal.font is allowed to be an OTF file too

### ISSUE THREAD

**Issue by ajgrf** [t184256/nix-on-droid#230]
The docs for `terminal.font` currently say that it “must be a path to a TTF font,” however OTF files work fine as well (the link name must be `font.ttf` regardless). TTC files also appear to work, but because TTC files are basically a bunch of TTFs wrapped up into a single file, there’s no way to control which typeface gets used.

So almost every font package in nixpkgs can be used by nix-on-droid. I think it would be good to reflect this in the docs.

**Comment by Gerschtli** [comment]
Fixed with #234
