### ISSUE TITLE
F-Droid 0.118 apk is smaller than before

### ISSUE THREAD

**Issue by linsui** [t184256/nix-on-droid#237]
0.66 apk is 19M but 0.118 apk is 3.7M only. Is this expected? I can't install the bootstrap packages but I don't know if it's my fault.

**Comment by t184256** [comment]
Bootstrap error: my fault (published prerelease, but not release), please retry now. Thanks a lot for reporting.

APK shrinking: Why not, I have nothing against it.

**Comment by linsui** [comment]
> APK shrinking: Why not, I have nothing against it.

So this is expected?

> please retry now

There is no tag. Should I just disable 0.118 and wait for the next version?

**Comment by t184256** [comment]
> So this is expected?

This isn't surprising, it's jumped from 0.66 to 0.118, might've gone smaller. The one I'm running for months now is 8MB and it works.

> There is no tag.

What does this mean?

> Should I just disable 0.118 and wait for the next version?

No, the APK in F-Droid is fine, the problem is somewhere else.

**Comment by t184256** [comment]
More specifically:

* when you install 0.118.0_v0.3.1_nix from F-Droid, and run it, does it offer to bootstrap from https://nix-on-droid.unboiled.info/bootstrap-release-22.11?
* when you agree, does it download and proceed to terminal or abort and produce a notification with an error?
* in any case, what is the error?

**Comment by t184256** [comment]
Glad to hear it's resolved.
