### ISSUE TITLE
Could not install packages due to an OSError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by M05QU170** [t184256/nix-on-droid#246]
Hi there I'm trying to install few packages through pip but I'm getting this error:

ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/nix/store/f2x987ir7wmyxbil5qw25dh6wscxkmrb-python3-3.10.9-env/lib/python3.10/site-packages/text_unidecode' Check the permissions.

I checked permissions in this folder and it should done but I'm not sure where the problem lies.
Is there easy way to install packages using pip or everything has to be done with config.nix or nix-env?

**Comment by t184256** [comment]
> everything has to be done with config.nix?

pip isn't expected to work in Nix world. Maybe you can make it work on a bet, but you'll have to fight your way through. Please use the (superior) way of Nix: https://nixos.org/manual/nixpkgs/stable/#python

**Comment by M05QU170** [comment]
> everything has to be done with config.nix?
> pip isn't expected to work in Nix world. Maybe you can make it work on a bet, but you'll have to fight your way through. Please use the (superior) way of Nix: https://nixos.org/manual/nixpkgs/stable/#python

I thought so.
