### ISSUE TITLE
Tasker Support

### ISSUE THREAD

**Issue by shadowrylander** [t184256/nix-on-droid#247]
Hello!

Is there any possibility of implementing Tasker support? The development possibilities would be endless!

Thank you kindly for understanding!

**Comment by Gerschtli** [comment]
What do you mean with Tasker support?

**Comment by shadowrylander** [comment]
Basically something like this?
https://github.com/termux/termux-tasker

Tasker is one of the most powerful automation applications on Android:
https://tasker.joaoapps.com/

I would love to be able to test my nix applications and push to GitHub automatically using Android shortcuts, for example!

**Comment by Gerschtli** [comment]
Sounds like android app work, unfortunately we don't have much knowledge about this android stuff, so any contributions are welcome (see https://github.com/t184256/nix-on-droid-app)..

**Comment by shadowrylander** [comment]
Is there no way to fork the plugin so that it works with the current app? Like, change some hooks or intents? Sorry, I don't actually know anything about Android development either. I understand there may be a lot of changes to make, but it seems straightforward enough to simply redirect them from the Termux app to Nix-On-Droid? Also, there didn't seem to be any way of creating an issue on that repo.

**Comment by Gerschtli** [comment]
Yeah, it could be straightforward but I can not even do that with my limited android expertise currently. Need to invest some time into this sometime in the future :tm:

This repo here is mainly used for issue tracking to not need to maintain two issue lists of tightly coupled projects.

**Comment by shadowrylander** [comment]
Oh, no; I understand. Is there nowhere else I can ask about this, though?

**Comment by Gerschtli** [comment]
@t184256 may have some more input but this repo's issues is the place for it. There is a [matrix room](https://matrix.to/#/#nix-on-droid:matrix.org) where you can ask but there are not that many people yet :D Also judged by the rather stale issues with the "android expertise needed" sadly there still is some contributiors with android knowledge missing for this project..

**Comment by shadowrylander** [comment]
Ah; I understand. Ah, well. I'll see what I can do. Thanks for all the information!
