### ISSUE TITLE
[FR] 23.05

### ISSUE THREAD

**Issue by FossPrime** [t184256/nix-on-droid#268]
please  update to 23.05... it's a huge leap and has better support for node, mongo and gpac...

First time using it today... Took forever to install on Pixel Fold... Compared to the fast installs NestBox w NixOS achieves on other Pixels.

Also, how is `clear` not working in an interactive bash terminal. I'm using flakes.

I just want to run replit.nix files.

**Comment by t184256** [comment]
> please update to 23.05... it's a huge leap and has better support for node, mongo and gpac...

Sure. https://github.com/t184256/nix-on-droid/pull/267 is a pull request for releasing a 23.05 update, I was planning to release it later today.

> First time using it today... Took forever to install on Pixel Fold... Compared to the fast installs NestBox w NixOS achieves on other Pixels.

The slowness is expected and is the price we pay for supporting a wide range of non-rooted devices. I hope in the bright future we'll all have VMs in our phones and this project will no longer be needed anymore. But so far, KVM is exclusive to select Pixel models, isn't it?

> Also, how is clear not working in an interactive bash terminal.

WDYM "clear not working"? Do you have it installed (it should be in `ncurses`).

> I just want to run replit.nix files.

Nice, replit is using Nix.

**Comment by t184256** [comment]
Forgot to close when https://github.com/t184256/nix-on-droid/pull/267 landed.
