### ISSUE TITLE
The https://nix-on-droid.unboiled.info/bootstrap-release-22.11/bootstrap-arm.zip not found

### ISSUE THREAD

**Issue by Parth589** [t184256/nix-on-droid#269]
There is only the zip file named 
https://nix-on-droid.unboiled.info/bootstrap-release-22.11/bootstrap-aarch64.zip

And the prompt says it needs to have the bootstrap-arm.zip. 

Where can i find that?

**Comment by t184256** [comment]
Sorry, you can't. This project doesn't support 32-bit ARM devices, you'll have to upgrade to a 64-bit one (~2015).
