### ISSUE TITLE
Nix on droid 

### ISSUE THREAD

**Issue by Piklubabu** [t184256/nix-on-droid#271]
Installed app but there is bootstrap error.

**Comment by t184256** [comment]
On July 7, 2023 1:35:44 PM GMT+02:00, Piklubabu ***@***.***> wrote:
>Installed app but there is bootstrap error. 
>

And what's the error?

**Comment by Piklubabu** [comment]
Unable to install bootstrap. Device Is 32 bit.

**Comment by t184256** [comment]
32 bit is not supported, sorry.
