### ISSUE TITLE
Cannot suppress login message

### ISSUE THREAD

**Issue by thecatvoid** [t184256/nix-on-droid#272]
How can i disable, "Welcome to Nix-on-Droid!
If nothing works, open an issue at https://github.com/t184256/nix-on-droid/issues or try the rescue shell." login messsge? I tried ```touch .hushlogin``` and it is not working.

**Comment by Gerschtli** [comment]
There is the `environment.motd` option which you can set to `null`, see https://t184256.github.io/nix-on-droid/nix-on-droid-options.html#opt-environment.motd :)

**Comment by thecatvoid** [comment]
That worked, I should have read the docs, thank you! Closing...
