### ISSUE TITLE
Fix app links and support email

### ISSUE THREAD

**Issue by agnostic-apollo** [t184256/nix-on-droid#276]
Hi, you have not changed the github organization name and support email in your fork. We have been receiving bootstrap installation errors and crashes for your app on our support email. Kindly set them to your own or add yours, thanks. You can still redirect any issues for termux app itself to us.

https://github.com/t184256/nix-on-droid-app/blob/65adc08590dbeef017f48e1b06be8c559a2dfc17/termux-shared/src/main/java/com/termux/shared/termux/TermuxConstants.java#L328

https://github.com/t184256/nix-on-droid-app/blob/65adc08590dbeef017f48e1b06be8c559a2dfc17/termux-shared/src/main/java/com/termux/shared/termux/TermuxConstants.java#L549

Latest one for reference.

```shell
java.io.FileNotFoundException: https://nix-on-droid.unboiled.info/bootstrap-release-23.05/bootstrap-arm.zip
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:259)
at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
at java.net.URL.openStream(URL.java:1072)
at com.termux.app.TermuxInstaller$2.run(TermuxInstaller.java:189)
```
https://nix-on-droid.unboiled.info/bootstrap-release-23.05/

**Comment by t184256** [comment]
Very sorry for this oversight, hope that didn't generate too much extra load for your team.

I've changed the constants you've pointed at and I hope F-Droid will be quick with building the new version.

Thank you.

**Comment by agnostic-apollo** [comment]
Only received a few emails till now, so not too much work till now. Thanks for the quick changes. You are welcome.
