### ISSUE TITLE
remote builder (using qemu for aarch64)?

### ISSUE THREAD

**Issue by bbigras** [t184256/nix-on-droid#62]
I think many packages need to be compiled on my phone when I update. I takes a while and use my battery.

Anyone uses a [remote builder](https://nixos.wiki/wiki/Distributed_build)? I wonder how to set up a remote builder using qemu to build the aarch64 packages for android on my x86_64 machine.

**Comment by t184256** [comment]
I don't, and I'd like to learn how to do it as well.

Note, that the performance likely won't be great with QEMU ARM emulation either. I wouldn't be surprised if faster IO due to the lack of proot would be the deciding factor, and not the CPU performance.

**Comment by bbigras** [comment]
I'm testing with some qemu overlay. Any way to make `nix-on-droid` pass `--builders` to `nix-build`? or define `nix.buildMachines` in some config?

**Comment by bbigras** [comment]
I think it's working but really really slow.

I'm using the qemu overlay from https://github.com/bqv/nixos (thanks to qy on the [matrix channel](https://matrix.to/#/#nix:matrix.org)).

qemux.nix: https://github.com/bqv/nixos/blob/live/profiles/misc/qemu.nix
overlay: https://github.com/bqv/nixos/tree/live/overlays/qemu

I'm creating a "builder" user on the builder machine.

builder host configuration.nix
```nix
let
  qemuOverlay = (import ./overlays/qemu);
in
{
  imports = [ ./qemu.nix ];

  boot.kernelModules = [ "kvm-intel" ];
  qemu-user.arm = true;
  boot.binfmt.emulatedSystems = [ "aarch64-linux" ];

  nix = {
    trustedUsers = [ "bbigras" "builder" ];
  };

  users.users.builder = {
    createHome = true;
    isNormalUser = true;
    # I should probably add the ssh pub key here
  };
}
```

on Android:
~/.config/nix/nix.conf
```conf
builders-use-substitutes = true
builders = ssh://builder
```

~/.ssh/config
```conf
Host builder
    HostName <the ip>
    User builder
    IdentitiesOnly yes
    IdentityFile ~/.ssh/nix_remote
```

~/.ssh/nix_remote is an ssh key without a password. I added the pub key on the builder machine.

you need to ssh first to the host to make ssh accept the host key.

You can test with `nix build '(with import <nixpkgs> { }; runCommand "foo" {} "uname -a > $out")' --builders 'ssh://builder' -j0`

or `nix-on-droid switch --max-job 0`

**Comment by t184256** [comment]
Cool. Could you please add this to https://github.com/t184256/nix-on-droid/wiki, so that it ain't buried in a closed issue?

**Comment by bbigras** [comment]
> Cool. Could you please add this to https://github.com/t184256/nix-on-droid/wiki, so that it ain't buried in a closed issue?

Yes no problem.

I have a question. Why bat needs to be built when running `nix-shell -p bat` on Android but it can be fetched from the cache when I build it manually on the builder machine? (on the 20.03 tag of nixpkgs).

```
❯ nix-build -A bat --argstr system aarch64-linux
these paths will be fetched (1.76 MiB download, 5.14 MiB unpacked):
  /nix/store/q97pn1hp62yik0s9ci3as5n0pabz8rsw-bat-0.12.1
copying path '/nix/store/q97pn1hp62yik0s9ci3as5n0pabz8rsw-bat-0.12.1' from 'https://cache.nixos.org'...
```

**Comment by t184256** [comment]
I'm afraid I don't know.

**Comment by Gerschtli** [comment]
Maybe its due to the bionic build env? I don't really understand that in detail but wasn't this the reason proot hash is different when compiled on the build host vs the phone? @t184255

**Comment by t184256** [comment]
No, it's not. Inside proot we don't use bionic.

**Comment by t184256** [comment]
@bbigras, is it possible to check if your builder would use the cache if you use same channel url? And will the hashes match?

**Comment by bbigras** [comment]
Sorry it took me a whole month to reply. I just added the stuff to the wiki.

> is it possible to check if your builder would use the cache if you use same channel url? And will the hashes match?

Like this?

```
❯ cd ~/nixpkgs
❯ git checkout 20.03
❯ nix-build -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-20.03.tar.gz -A bat --argstr system aarch64-linux
these paths will be fetched (8.48 MiB download, 37.53 MiB unpacked):
  /nix/store/2sgk68v38wj5fc264b8nl2znz8j1ijf8-ncurses-6.1-20190112
  /nix/store/2vn35phq7d4q3q6pi6jipxy1h1x3346s-glibc-2.30
  /nix/store/lm6rckx5z0j3qr5y2a63figa61a6n6p4-less-551
  /nix/store/q97pn1hp62yik0s9ci3as5n0pabz8rsw-bat-0.12.1
  /nix/store/qa79fvrbxrgxx9pl1yqjmv82183z6n4s-bash-4.4-p23
copying path '/nix/store/2vn35phq7d4q3q6pi6jipxy1h1x3346s-glibc-2.30' from 'https://cache.nixos.org'...
copying path '/nix/store/qa79fvrbxrgxx9pl1yqjmv82183z6n4s-bash-4.4-p23' from 'https://cache.nixos.org'...
copying path '/nix/store/2sgk68v38wj5fc264b8nl2znz8j1ijf8-ncurses-6.1-20190112' from 'https://cache.nixos.org'...
copying path '/nix/store/lm6rckx5z0j3qr5y2a63figa61a6n6p4-less-551' from 'https://cache.nixos.org'...
copying path '/nix/store/q97pn1hp62yik0s9ci3as5n0pabz8rsw-bat-0.12.1' from 'https://cache.nixos.org'...
/nix/store/q97pn1hp62yik0s9ci3as5n0pabz8rsw-bat-0.12.1
```

**Comment by bbigras** [comment]
On Android bat seems to come from the cache right now. I'll check if it's the same hashes.

**Comment by bbigras** [comment]
If I run `nix-env -f https://github.com/NixOS/nixpkgs/archive/48723f48ab92381f0afd50143f38e45cf3080405.tar.gz -i bat` on my phone and `nix-env -f https://github.com/NixOS/nixpkgs/archive/48723f48ab92381f0afd50143f38e45cf3080405.tar.gz -i bat --argstr system aarch64-linux` it seems to fetch same thing from the cache.

Maybe the problem with bat is gone.

Is there any way to know which derivations need to be built?

![image](https://user-images.githubusercontent.com/24027/83296896-8aef8580-a1bf-11ea-9cf1-a0124840ba41.png)

**Comment by bbigras** [comment]
If we forget the remote builder for a sec.

If I want run nix-on-droid but only use cached stuff, no local build, can I use `--max-jobs 0` or there's at least 1 derivation that need to be build locally. Like for my config.

**Comment by Gerschtli** [comment]
Try to run `nix-build "<nix-on-droid/modules>" -A activationPackage` and ctrl-c the command after the list of to be built packages is shown, if thats what you want.

**Comment by bbigras** [comment]
Thanks everyone.

My nix-on-droid doesn't seem to want to build stuff currently. Maybe I was on a different channel before I wiped to make openssh work. I'll open a new issue if I see it again in the future.

**Comment by 573** [comment]
Hi @bbigras,

what you had set up there is exactly the use case me and sure many others aim for.

I wanted to try this as well. To better get a grip how things relate and since I do not own a machine with NixOS installed and hence have no `configuration.nix` file anywhere I thought I would do that in a vm with NixOS installed inside first, meaning what is the remote builder in your wiki example would be a qemu (aarch64-linux as on my phone) vm running NixOs. So far I [have](https://gist.github.com/573/c1d73a4fd04b8f8ca63885393856f9ea) in a folder `remote-builder-nix`:

```
# vm-config.nix from the link above modified
{ pkgs, lib, ... }:

with lib;
let
  qemuOverlay = (import ./overlays/qemu);
in
{
  imports = [
    <nixpkgs/nixos/modules/profiles/qemu-guest.nix>
    ./qemu.nix
  ];

  config = {
    fileSystems."/" = {
      device = "/dev/disk/by-label/nixos";
      fsType = "ext4";
      autoResize = true;
    };

    # Set VM disk size (in MB)
    virtualisation.diskSize = 1024 * 2048;

    boot.growPartition = true;
    boot.kernelModules = [ "kvm-intel" ];
    boot.kernelParams = [ "console=ttyS0" ];
    boot.loader.grub.device = "/dev/vda";
    boot.loader.timeout = 0;

    i18n.defaultLocale = "de_DE.UTF-8";
    time.timeZone = "Europe/Paris";

    services = {
      timesyncd.enable = lib.mkDefault true;
      openssh = {
        enable = true;
        permitRootLogin = "yes";
      };
    };

    environment.systemPackages = with pkgs; [
      vim curl
    ];

    qemu-user.arm = true;
    boot.binfmt.emulatedSystems = [ "aarch64-linux" ];

    nix = {
      trustedUsers = [ "573" "builder" ];
    };

    users.extraUsers.root.password = "";
    users.mutableUsers = false;

    users.users.root = {
      extraGroups = [ "wheel" ];
      openssh.authorizedKeys.keys = [
        "ssh-rsa ... "
      ];
    };
    users.users.builder = {
      createHome = true;
      isNormalUser = true;
    };
  };
}
```

`vm.nix` as in my link above as well as the overlay dir and `qemu.nix` from your links given.

To build the vm I would now i. e. run:

> $ nix-build '<nixpkgs/nixos>' -A vm -I nixos-config=vm.nix

but that gives me 

> error: attribute 'qemu-user-arm64' missing, at /home/573/remote-builder-nix/qemu.nix:11:22

How is that ? Where would the

**Comment by 573** [comment]
FYI, I leave a [tracking link](https://discourse.nixos.org/t/how-to-configure-qemu-binfmt-wrapper-on-a-non-nixos-machine/7879) here, where I discuss approaching a working template.

**Comment by 573** [comment]
Sorry for the gruft added by the last two posts.
I added a [wiki entry](https://github.com/t184256/nix-on-droid/wiki/Same-machine-remote-builder-how-to) with my findings, spoiler it works now in a vm on the same metal/machine.

**Comment by t184256** [comment]
I find the page confusing, TBH. It elaborates on https://github.com/t184256/nix-on-droid/wiki/Use-a-remote-builder-with-qemu, and enhances it with a way to spawn such builder VMs on anything Nix-capable, right? Could you somehow make it more clear in the introduction?

Also, wow, let's offload compilation from Nix-on-Droid to WSL1. You, sir, win a unique setup award.

**Comment by 573** [comment]
@t184256 thx I'm honored lol.

But yes indeed using this approach I'm able to compile packages for nix-on-droid the aarch64 architecture on a vm spawned as you said exactly. the vm running nixos but the metal spawning the vm just using nix which latter part is just conveniency.

the point is that i can't access certain ressources outside of a vpn due to disabled dns splitting and so I had to use this quasi dns-agnostic approach. side effect, finally there is a machine running NixOS for me as well.

I am trying to make the article more comprehensive with a better intro soon. Thanks for your input.

**Comment by t184256** [comment]
Thanks for following through! I definitely like the new version better.
