### ISSUE TITLE
nix-on-droid-session-init.sh uses $HOME before setting $HOME

### ISSUE THREAD

**Issue by t184256** [t184256/nix-on-droid#63]
I've just noticed that `nix-on-droid-session-init.sh` seems to source `$HOME/.nix-profile/etc/profile.d/nix.sh` before setting `$HOME`.

@Gerschtli, you might be interested.

**Comment by Gerschtli** [comment]
Maybe we should just hardcode `$HOME` because it will never change, see `config.user.home`.

**Comment by t184256** [comment]
Closed through cb0905a4a03c5a54602d7240e66be08f73beb7b2.
