### ISSUE TITLE
Any easy way to edit my config file from my computer?

### ISSUE THREAD

**Issue by bbigras** [t184256/nix-on-droid#66]
adb doesn't give us access to `com.termux.nix` right?

I know I could use openssh but it didn't work well with emacs tramp.

Right now I'm using openssh with scp.

I wonder if someone has a neat approach for this.

**Comment by Gerschtli** [comment]
I've never used adb before but I think it should be safe to test running the `/data/data/com.termux.nix/files/usr/bin/login` script, which should put you into the proot env similar to creating a new session in the app.

**Comment by t184256** [comment]
out of the box: IIRC there were remote control solutions over adb
