### ISSUE TITLE
CI fails, Travis Nix (2.0.4) is too old

### ISSUE THREAD

**Issue by t184256** [t184256/nix-on-droid#67]
@Gerschtli, could you please take a look?

```
$ nix-env --version
nix-env (Nix) 2.0.4
$ nix-instantiate --eval -E 'with import <nixpkgs> {}; lib.version or lib.nixpkgsVersion'
error: evaluation aborted with the following error message: '
This version of Nixpkgs requires Nix >= 2.2, please upgrade:
- If you are running NixOS, `nixos-rebuild' can be used to upgrade your system.
```

(https://travis-ci.org/github/t184256/nix-on-droid/builds/697755958)

**Comment by Gerschtli** [comment]
You could try adding `nix upgrade-nix` in the `before_install` section of `.travis.yml`..

**Comment by t184256** [comment]
That fixed it, thanks a lot!

**Comment by abathur** [comment]
Just wanted to let you know that Nix support is working on Travis again, and the default version is updated to 2.3.6, as of about an hour ago.
