### ISSUE TITLE
Unable to upgrade nix-channels

### ISSUE THREAD

**Issue by atmorojo** [t184256/nix-on-droid#68]
Hello, I'm trying to run nix on my Android 6 machine. Bootstrap downloaded succesfully. But I'm stuck on first update of the nix-channels. Read somewhere it probably has something to do with https, so I edited the .nix-channels from failsafe. But apparently after I closed the failsafe the content of .nix-channels is reverted back to before I edited it.

I'm new with nix so I kinda clueless. What can I do to fix this?

Thank you.

**Comment by t184256** [comment]
Could you please do a clean reinstall and post the installation output in its entirety through gist.github.com or a similar service?

Could you please elaborate more on why do you suspect https is the issue?

**Comment by atmorojo** [comment]
Sorry for taking my time to come back to this issue. I guess it's my last ISP doing weird things. I changed my ISP today and everything is installing properly. Now I'm on bash already.

Thank you for your hard work and sorry for making a fuss over this. I'm closing the issue.
