### ISSUE TITLE
root certificates missing?

### ISSUE THREAD

**Issue by bbigras** [t184256/nix-on-droid#69]
I got this message when I try to use `niv`:

![image](https://user-images.githubusercontent.com/24027/87212591-53f7ae00-c2ed-11ea-81ef-51518a482780.png)

I have `cacert` installed.

I also have a similar message when I try to push stuff to cachix.

Any ideas?

**Comment by t184256** [comment]
Wild guess: https://knowledge.digicert.com/alerts/DigiCert-ICA-Replacement

**Comment by ahdyt** [comment]
Hi I have workaround for this issue

First install curl

Then mkdir at /etc/ssl/certs

cd there and run

```curl --remote-name --time-cond cacert.pem https://curl.se/ca/cacert.pem```

Perhaps there's one who like to make automated script, that would be useful.

**Comment by Gerschtli** [comment]
A more robust solution would be to add
```nix
{
  environment.etc."ssl/certs/ca-certificates.crt".source = "${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt";
}
```
Or a modified version of https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/security/ca.nix.

Maybe anyone has the time to add such a module to nix-on-droid to fix it for all users :)

**Comment by ahdyt** [comment]
> Maybe anyone has the time to add such a module to nix-on-droid to fix it for all users :)

the module still foreign for me
