### ISSUE TITLE
New to nix-on-droid

### ISSUE THREAD

**Issue by mrfoxie** [t184256/nix-on-droid#72]
can I get commands detail as well as wiki to use this application 

thanks in advance

**Comment by Gerschtli** [comment]
Essentially you are in a basic nix environment without super user privileges. You can use the manual of nix and nixpkgs on https://nixos.org as a starting point.

Additionally a executable named `nix-on-droid` is available which tries to mimic nixos-like behaviour (see `~/.config/nixpkgs/nix-on-droid.nix` for configuration file).

In the Readme of this repository are some information about how to use `nix-on-droid`. Unfortunately there is no easy way to search for available options as this project is in an early stage. So you can look into the `modules` folder for discovering more options.

The recommended setup includes home-manager which is documented quite good. For instructions on how to embed home-manager into nix-on-droid see the Readme.

I hope this helps :)

**Comment by Gerschtli** [comment]
The issue relating to the missing documentation of available options is https://github.com/t184256/nix-on-droid/issues/36.

**Comment by mrfoxie** [comment]
I tried to use this command `nix-env -qaP \*` and it gave me error like this`FAILED`

**Comment by Gerschtli** [comment]
Can you give me more information (e.g. smartphone model, ram size) and a way to reproduce this error beginning from a clean install because for this command works (quite slowly but it works)?

**Comment by mrfoxie** [comment]
this is my phone [vivo 1808](https://www.gsmarena.com/vivo_y71i-9358.php) and I tried to reinstall the app by uninstalling it completely and fresh install it

**Comment by Gerschtli** [comment]
`nix-env -qaP \*` is a really inperformant command because it tries to evaluate the whole nixpkgs. I think 2GB of RAM aren't sufficient.

So this is not a fixable issue in nix-on-droid unfortunately..

**Comment by lypanov** [comment]
Easiest workaround to this issue is to use the website to search: https://search.nixos.org/packages

Even on a Samsung Tab S6 nix based package search is too slow to be useful.

**Comment by t184256** [comment]
Can you post the output?

`nix-env` works fine for me provided I have `gzip` installed. In general, you're supposed to add packages to the configuration file and `nix-on-droid switch` instead of using `nix-env`.
