### ISSUE TITLE
Donate/contribute to Nix-on-Droid

### ISSUE THREAD

**Issue by scolobb** [t184256/nix-on-droid#79]
I have been using Nix-on-Droid for a couple of days, but it has already allowed to me to install my favorite tools (Emacs) on my Android phone, which is incredibly helpful for my work.

How can I buy you a coffee/multiple coffees? :slightly_smiling_face: 

I've been using Nix for quite a while on my main laptop, but my knowledge of Nix and especially Android is too limited for me to be useful on the technical side of the project.  Nevertheless, if you have suggestions, please do tell me: maybe not everything is beyond my reach.

**Comment by t184256** [comment]
Thanks for your kind words =)

I've never dealt with donations before, I'm knee-deep in other projects these days and I don't drink coffee,
so I'll gladly pass this question to @Gerschtli. I own him quite a pack of something at this point =)

Technical contributions are, obviously, always welcome.
A bit of categorizing of the technical involvement levels, on a scale of most effort to least effort:

1) Fork the repo, build it from scratch and bootstrap from the result.
Might be somewhat tedious, esp. if you don't have a second device.
The good thing is, the vast majority of the time you don't need to (even I don't need to),
unless you want to test some really invasive low-level fundamental changes.
You gotta be rebasing proot or nixpkgs or touching installation stuff to really need that.
Instead, you can just...

2) Fork the repo, point your device to the fork, push and try out changes.
Enhance scripts, fix typos, add overlays to accommodate your favourite package
to the combined Android, proot and Nix-on-Droid pecularities
(I even heard folks considering semi-automating it in #78).
Make backups, of course, but, all-in-all,
such exploration should be pretty harmless and reversible.

3) Just use it, and don't hesitate to ask questions / share findings.
Contributing some neat trick to the wiki or going through the issues,
picking something you can reproduce and reporting the results could be an good start.
Or, you know, use it some more and report issues, there should be plenty =)

And last, but definitely not least, consider contributing to Nix/nixpkgs.
The fact you're happily using them on your phone now
is [a direct consequence of their phenomenal awesomeness and flexibility](https://youtu.be/vwBxGVF3VS0?t=1484).
They're the real gem here, and much more people will benefit from your contribution there,
including, of course, NIx-on-Droid users.

**Comment by scolobb** [comment]
Thank you for you detailed answer @t184256 ! I don't drink coffee either, but I use this word to designate any potentially useful commodity :smile: 

In what concerns contributions, I will start with 3 obviously, potentially crawling into 2 (seems to be within my reach).

In what concerns Nixpkgs, I have already made some contributions there, but now that I have another device running Nix, I'll probably get even more motivation to contribute.

**Comment by Gerschtli** [comment]
Haha, thank you @t184256 but I think contributing to NIx, Nixpkgs and/or Nix-on-Droid would be the better approach instead of donating, but it is nice to hear that Nix-on-Droid gets appreciated :)

And a good thing to start is as always documentation. Especially someone who does not have big knowledge about the internals has another point of view. So if you think, something in the README, the wiki or whatever is missing or not clear enough, open an issue or if you can and want to open a PR.

**Comment by scolobb** [comment]
Thank you @Gerschtli ! You're right about the docs, I'll think how I can contribute.  The docs are always a good starting point.
