### ISSUE TITLE
Using home-manager how is nix.conf managed on nix-on-droid ?

### ISSUE THREAD

**Issue by 573** [t184256/nix-on-droid#83]
Regularly I can (in home.nix)

```
home.file = {
  nixConf = { text = ''''; };
};
```

which does not do on nix-on-droid so, if that did not work I could have tried

```
xdg = {
    enable = true;
    configFile."nix/nix.conf".text = '''';
};
```

which also seems to not work as it complains

>Error installing file '.config/nix/nix.conf' outside $HOME

thus testing in nix repl that

```
nix-repl> builtins.getEnv "HOME"
```

gives

>"/data/data/com.termux.nix/files/home"

I set

```
let
  homedir = builtins.getEnv "HOME";
xdg = {
    enable = true;
    configHome = "${homedir}/.config";
    configFile."nix/nix.conf".text = '''';
};
```

again getting

>Error installing file '.config/nix/nix.conf' outside $HOME

but using that the nix.conf is though written not filled with the correct set of data

```
let
  homedir = /data/data/com.termux.nix/files/home;
in {
  xdg = { (...) }
}
```

so I resorted to
```
home.file = {
  ".config/nix/nix.conf".text = '''';
};
```

which feels pretty not the way things ought to be done but it works for now.

Has someone ideas where I can possibly have taken wrong steps ?

**Comment by 573** [comment]
I learned something new about syntax.

Using

```
home.file = {
  nixConf = {
    text = ''
      # hello nix.conf
    '';
  };
};
```

things work as expected with `nix.conf`.

Also the `xdg` management is working, sample using defaults:

```
xdg = {
  enable = true;
  configFile = {
    "hello-xdg/hello.conf".text = ''
      show-home: ${toString config.home.homeDirectory}
    '';
  };
};
```

**Comment by t184256** [comment]
Reopening to remember to double-check it's OK.

**Comment by Gerschtli** [comment]
@573 AFAICT your code snippets in your original description and your last comment seem to be identical.

```
home.file = {
  nixConf = {
    text = ''
      # hello nix.conf
    '';
  };
};
```
This should generate a file called `~/nixConf`, does this actually write to `~/.config/nix/nix.conf`?

**Comment by 573** [comment]
@Gerschtli it writes the latter and it seems [expected to] (https://github.com/cachix/cachix/issues/239#issuecomment-654868603) do so.

**Comment by Gerschtli** [comment]
Ah, just checked your repo and found https://github.com/jonascarpay/nix/blob/3840e6c20ff46e173600057eb490f8005f0787a7/home-modules/caches.nix#L92
```nix
{
  config.home.file.nixConf = {
    target = ".config/nix/nix.conf";
    text = nixConfSource;
  };
}
```
With this option it works of course. This was a crucial part of your config. For future issues you should always add a complete minimal reproduction config snippet :) So this issue seems fine to me, will close it, but feel free to reopen if necessary.
