### ISSUE TITLE
~/storage equivalent

### ISSUE THREAD

**Issue by lypanov** [t184256/nix-on-droid#85]
I've been looking into what it would take to introduce ~/storage to nix-on-droid (TermuxArch for example has it) but I'm a massive nix newbie and found it quite difficult to figure out where the needed bind would need to be added.

Have you already looked into this by any chance?

Thank you!
Alex

**Comment by t184256** [comment]
What is it and what does it do?

At least on my Android 9, if you allow storage access in the app settings (reachable through Android settings), you can then access your sdcard through regular Android paths, is this what you're after? You can symlink it as `~/storage` then.

**Comment by lypanov** [comment]
For future reference for anyone else looking for this feature coming from Termux lang. An example such path is `/storage/emulated/0/Download` (not sure if this is universal).

Thank you! Closing the ticket as the remaining stuff is usability, and I don't forsee many nix users complaining about that.
