### ISSUE TITLE
ping: unknown protocol icmp: missing /etc/protocols

### ISSUE THREAD

**Issue by tobiasBora** [t184256/nix-on-droid#86]
If I install ping using:

    nix-env -iA nixpkgs.inetutils

And try to ping any website I get an error:

     ping: unknown protocol icmp

It seems that a file /etc/protocols must be created, and I guess it's the role of the OS to create that file. Would it be possible to populate this file by default?

Thanks!

**Comment by Gerschtli** [comment]
For a temporary fix, you can create this file with the necessary content via
```nix
{
  environment.etc."protocols".text = "...";
}
```

Another way would be to create a PR to add a sensible /etc/protocols for every installation. Looking forward to any contribution to make this project more robust :)

**Comment by Gerschtli** [comment]
I had a look at what NixOS does, I think this would be sensible way to add /etc/protocols and maybe /etc/services too.

See https://github.com/NixOS/nixpkgs/blob/921a4ec9c173ca18e824eb97774c2d6dc3e0a2e4/nixos/modules/config/networking.nix#L189

**Comment by t184256** [comment]
I hate to ruin the fun, but wouldn't ICMP-based ping need root privileges for raw socket access?

I'm afraid only things like `mtr -u` could work.

**Comment by t184256** [comment]
@Gerschtli has implemented this in 4e928be3e81e5a56e4276b288e799b14898f64ce
