### ISSUE TITLE
Where to find changelog ?

### ISSUE THREAD

**Issue by 573** [t184256/nix-on-droid#87]
In the [config file](https://github.com/t184256/nix-on-droid/blob/886fbb050eecb5105b3a24aa5db19ad087a47c1b/modules/environment/login/nix-on-droid.nix.default#L31) we have a mention of the changelog.

># Read the changelog before changing this value

Where actually do I find that changelog ? 

Let's say I wanted to upgrade nix from 2.3.6 to 2.3.7 and therefor use another nixpkgs channel.

Is this foreseen or not yet ?

**Comment by Gerschtli** [comment]
Oh thanks for the heads up. Indeed we do not have any Changelog yet. We should definitely create one, so please keep this issue open as long as it is missing.

The stateVersion behaves similarly to these in NixOS and Home Manager, they reflect the version of state as NixOS version number. Currently this flag is not used anywhere and only the values 19.09 and 20.03 are allowed. We will add 20.09 and separate channel for it as soon as NixOS 20.09 is released.

**Comment by t184256** [comment]
This is for nix-on-droid defaults, and I don't think anything depends on it yet. We'll use it in 20.09 to flip useUserPackages to true (#65), nothing else. Feel free to proceed with your plans, this won't interfere.

**Comment by t184256** [comment]
Changelog is now published at https://github.com/t184256/nix-on-droid/blob/master/CHANGELOG.md
