### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [t184256/nix-on-droid#93]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by t184256** [comment]
I know, I just don't know what to show there. I mean, it's just a terminal.

**Comment by bbigras** [comment]
A nice prompt like starship or powerlevel10k. With an example of using nix-shell.

![Screenshot_20210105-202218](https://user-images.githubusercontent.com/24027/103717575-d6f37b80-4f93-11eb-847e-ac423e4bebb6.png)

![Screenshot_20210105-202235](https://user-images.githubusercontent.com/24027/103717593-e377d400-4f93-11eb-8e6e-b26a2bc4857e.png)

**Comment by t184256** [comment]
Interesting start!

-1 on 'nice prompt', we shouldn't show anything the user won't get out of the box. And it's highly opinionated.

+1 on a nix-shell usage example, though maybe it should be nix run?

+1 on *fetch, that seems to be common with linux screenshots (half a century of uptime?)

Maybe also cram nix-shelling a text editor, editing a config to add a package, `nix-on-droid switch`'ing and executing something freshly installed.

And it has to be in much larger letters.

**Comment by mondlicht-und-sterne** [comment]
Since the issue dates back a long time - can you just close
the issue? Thank you, my initial Issue was also just information.
