### ISSUE TITLE
No way to set cache sources

### ISSUE THREAD

**Issue by blinaa** [t184256/nix-on-droid#98]
Seems like nix on droid has a hardcoded nixos cache source, there are no trusted-public-keys and substituters keys in the config file.

**Comment by Gerschtli** [comment]
Currently nix.conf is configured in `modules/environment/files.nix`. We could move the config for nix.conf into a separate module, where you can set other cache sources.

If you want to contribute, feel free :) Don't know when I have time for it.

**Comment by blinaa** [comment]
So i can just add my cache sources in nix/nix.conf and it is going to work, am i right ?

**Comment by Gerschtli** [comment]
Yes, this is the file nix uses for these options.
